# Generated by Django 6.0.5 on 2026-05-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=150)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute')], default='Moyenne', max_length=10)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours de traitement'), ('Resolue', 'Résolue'), ('Rejetee', 'Rejetée')], default='En attente', max_length=20)),
                ('agent_assigne', models.CharField(blank=True, max_length=100, null=True)),
                ('reponse_agent', models.TextField(blank=True, null=True)),
                ('commentaire_interne', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_nom', models.CharField(max_length=100)),
                ('action_effectuee', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='agent.reclamation')),
            ],
        ),
    ]
